## Week 9 Lab Instructions:



In [22]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


# DF example:
# df = pandas.read_csv('C:\\Users\\travis\\OneDrive - University of New Haven\\Class Materials\\Fall 2020\\Week 9\\US Census Data\\census_data.csv')

### 1. Return to the US Census Income Dataset from previous weeks
    * We are very familiar with this data at this point.
    * Instantiate the DataFrame in Pandas

In [2]:
col_names = [
    "Age", "WorkClass", "fnlwgt", "Education", "EducationNum",
    "MaritalStatus", "Occupation", "Relationship", "Race", "Gender",
    "CapitalGain", "CapitalLoss", "HoursPerWeek", "NativeCountry", "Income"
]

df = pd.read_csv('adult.csv')
df.columns=col_names
# df['Income'] = df['Income'].apply(lambda x: 0 if x == ' <=50K' else 1)

### 2. Split into training/testing sets

In [3]:
# Label Encoding
for column in df.columns:
    if df[column].dtype == type(object):
        le = preprocessing.LabelEncoder()
        df[column] = le.fit_transform(df[column])
df.tail()

Age  WorkClass  fnlwgt  Education  EducationNum  MaritalStatus  \
32556   22          4  310152         15            10              4   
32557   27          4  257302          7            12              2   
32558   40          4  154374         11             9              2   
32559   58          4  151910         11             9              6   
32560   22          4  201490         11             9              4   

       Occupation  Relationship  Race  Gender  CapitalGain  CapitalLoss  \
32556          11             1     4       1            0            0   
32557          13             5     4       0            0            0   
32558           7             0     4       1            0            0   
32559           1             4     4       0            0            0   
32560           1             3     4       1            0            0   

       HoursPerWeek  NativeCountry  Income  
32556            40             39       0  
32557            38             39       0  
32558            40             39       1  
32559            40             39       0  
32560            20             39       0

In [4]:
X = df.drop(columns=['Income'])
y = df['Income']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=555, stratify=y)

In [5]:
df.Income.unique()

array([0, 1], dtype=int64)

In [7]:
y.tail(3)

32558    1
32559    0
32560    0
Name: Income, dtype: int32

### 3. Build a DecisionTreeClassifier with 5 fold cross validation   
    * Note results 

In [8]:
dt = DecisionTreeClassifier()

In [9]:
# K-Fold with 5 fold cross validation
results = sklearn.model_selection.cross_val_score(dt, X_train, y_train, cv=5)
results

array([0.81122031, 0.80548731, 0.80773956, 0.80917281, 0.80896806])

In [10]:
results.mean(), results.std()

(0.8085176085176086, 0.0018828114549668553)

### 4. Using the bagging technique, build an ensemble with 100 base DecisionTreeClassifier trees
    * Note and compare results 

In [12]:
dt_bag = BaggingClassifier(base_estimator=dt, n_estimators=100, n_jobs=-1)

# Training the model
dt_bag.fit(X_train,y_train)

results_bag = dt_bag.score(X_test, y_test)
results_bag


0.8519837857757032

### 5. Lastly, build a RandomForestClassifier   
    * Note and compare results yet again

In [23]:
rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
rf.score(X_test, y_test)

0.855791671784793

In [25]:
res = rf.predict(X_test)
res

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
mserror_rf = sklearn.metrics.mean_absolute_error(res, y_test)
print("The mean Absolute Error for Random Forest is",mserror_rf*100,"%")

The mean Absolute Error for Random Forest is 14.4208328215207 %


In [ ]:
# Conclusion: Random Forest Classifier has more accuracy than Bagging using Decision Tree Classifier